feat: ヘッダーとサイドバー・サイドドロワーを実装
traPtitech/Checkin-UI pull request #16
Opened 2024-12-30 16:31 UTC by reiroop

サイドバー・サイドドロワーにはナビゲーションメニューを実装
postcss.config.js を修正し
Heroicons を依存関係に追加
テンプレートの不要なコンポーネントとcss を削除

2024-12-31 04:03 UTC, Pugma commented
見た感じ、 PC 画面で表示されるサイドバーでも `gap-2` が適用されてそうな気がします
適用されてない部分がもしありましたら、もう少し詳細に教えていただけないでしょうか…？
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/e60936e6-2eb1-4709-853d-b9e32908e3e5" />

2024-12-31 06:38 UTC, Pugma commented
色々確かめてみたんですが、そもそもサイドバーとサイドドロワーで表示したいものが同じなのに別の `.vue` ファイルを作っているのでややこしくなってそうかな〜と思いました
CSS も動的に付け替えることができるので、それを使ってみるともう少し簡素な実装にできそうです

2024-12-31 06:45 UTC, Pugma requested changes
とりあえずの問題点は見つけたので、ここだけまずは見てもらえればいいかなと思います

2024-12-31 06:45 UTC, Pugma commented on src/App.vue
> +    <SideNavigation class="hidden md:block" />
とりあえずは以下のようにすることで `gap-2` が有効になりました
メディアクエリで画面幅が 768 以上のときに `display: block;` が当てられていて、これと flex とが競合していたようです
```suggestion
    <SideNavigation class="hidden" />
```

2024-12-31 17:26 UTC, Pugma reviewed
ありがとうございます〜
とりあえず気になったのはこの辺りです…！
そんなに優先度が高いものではないので、お時間のあるときにご確認いただければと思います

2024-12-31 17:26 UTC, Pugma commented on src/layouts/SideNavigationButton.vue
> +const props = defineProps<Props>()
Vue 3.5 以降だと、こんな感じで分割代入をするとかなり簡単に props の各フィールドにアクセスできるようになるので使ってみると良いと思います
参考: https://ja.vuejs.org/guide/components/props#reactive-props-destructure
```suggestion
const { isHere, path, text } = defineProps<Props>()
```

2024-12-31 17:50 UTC, reiroop commented on src/layouts/SideNavigation.vue
> +      :is-here="route.path === '/membership'"
これに関しては、例えば一部のクエリパラメーターをURLの一致の判定の条件に含めたいケースを将来的に考えててこの実装にしてるつもり、つまり `route.path === props.path` をコンポーネント内部で実装しちゃうと困るケースを考えてる感じ

2024-12-31 18:36 UTC, Pugma commented on src/layouts/SideNavigation.vue
> +      :is-here="route.path === '/membership'"
なるほどです
であれば、この実装で大丈夫だと思います :+1:

2025-01-01 03:22 UTC, cp-20 commented on src/layouts/CheckinHeader.vue
> +    <ModalWrapper v-if="shouldShowModal" @click-outside="closeModal">
アクセシビリティ的には dialog 要素とかを使うと良い気はします (MUSTではないけど)

2025-01-01 03:24 UTC, Pugma approved these changes
コメントにも対応くださってありがとうございました
よさそうです！

2025-01-01 04:24 UTC, reiroop commented on src/layouts/CheckinHeader.vue
> +    <ModalWrapper v-if="shouldShowModal" @click-outside="closeModal">
わかんなかった、issue行き

2025-01-01 04:28 UTC, merged